auth:
  harvest:
    mail: 'kosta@savaslabs.com'
    pass: ''
    account: 'chrisrusso'
  redmine:
    user: 'kostajh'
    pass: ''
    url: 'http://localhost:9292'
sync:
  # Map a Harvest user ID to a redmine user ID. Required.
  users:
    785018: "redmine_username"
    123456: "another_user"
  projects:
    # Exclude Harvest project IDs from time entry processing.
    exclude:
      - "5990760"
      - "7077045"
      - "7174765"
