auth:
  harvest:
    mail: 'kosta@savaslabs.com'
    pass: ''
    account: 'chrisrusso'
  redmine:
    user: 'kostajh'
    pass: ''
    url: 'http://localhost:9292'
sync:
  users:
    785018: "redmine_username"
    123456: "another_user"
  projects:
    exclude:
      - "5990760"
      - "7077045"
      - "7174765"
    map:
      6110509: "Some project name in Redmine"
      1234567: "Another project name in Redmine"
